server:
  port: 8802
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: homework
          uri: lb://homework
          predicates:
            - Path=/**
        - id: register
          uri: lb://register
          predicates:
            - Path=/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/**
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8804/oauth/check_token

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
