
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 738761580@qq.com #发送邮件的邮箱地址
    password:  cakyclvmloyqbcdb #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 587 #端口号465或587
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

server:
  port: 8080
