#server:
#  port: 8805
#
#spring:
#  application:
#    name: homework
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8801/eureka/
#
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:8804/user
#      id: ${spring.application.name}
