server:
  port: 8805

spring:
  application:
    name: register
#  datasource:
#    username: root
#    password: 2568930409fz
#    url: jdbc:mysql://localhost:3306/homework?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database: mysql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8802/auth/user
