server:
  port: 8804

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
spring:
  application:
    name: auth
  datasource:
    username: root
    password: ehomework
    url: jdbc:mysql://3.227.208.8:3306/chp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      database: mysql
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  main:
    allow-bean-definition-overriding: true
