server:
  port: 8804

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
spring:
  application:
    name: auth
  datasource:
    username: root
    password: 2568930409fz
    url: jdbc:mysql://localhost:3306/homework?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      database: mysql
  main:
    allow-bean-definition-overriding: true
